# globex_logging.yaml
# Globex configuration file...
globex_setting_1: value_1
globex_setting_2: value_2
globex_setting_3: value_3
globex_setting_4: value_4
globex_setting_5: value_5
globex_setting_6: value_6
globex_setting_7: value_7
globex_setting_8: value_8
globex_setting_9: value_9
globex_setting_10: value_10
globex_setting_11: value_11
globex_setting_12: value_12
globex_setting_13: value_13
globex_setting_14: value_14
globex_setting_15: value_15
globex_setting_16: value_16
globex_setting_17: value_17
globex_setting_18: value_18
globex_setting_19: value_19
globex_setting_20: value_20
globex_setting_21: value_21
globex_setting_22: value_22
globex_setting_23: value_23
globex_setting_24: value_24
globex_setting_25: value_25
globex_setting_26: value_26
globex_setting_27: value_27
globex_setting_28: value_28
globex_setting_29: value_29
globex_setting_30: value_30
globex_setting_31: value_31
globex_setting_32: value_32
globex_setting_33: value_33
globex_setting_34: value_34
globex_setting_35: value_35
globex_setting_36: value_36
globex_setting_37: value_37
globex_setting_38: value_38
globex_setting_39: value_39
globex_setting_40: value_40
globex_setting_41: value_41
globex_setting_42: value_42
globex_setting_43: value_43
globex_setting_44: value_44
globex_setting_45: value_45
globex_setting_46: value_46
globex_setting_47: value_47
globex_setting_48: value_48
globex_setting_49: value_49
globex_setting_50: value_50
globex_setting_51: value_51
globex_setting_52: value_52
globex_setting_53: value_53
globex_setting_54: value_54
globex_setting_55: value_55
globex_setting_56: value_56
globex_setting_57: value_57
globex_setting_58: value_58
globex_setting_59: value_59
globex_setting_60: value_60
globex_setting_61: value_61
globex_setting_62: value_62
globex_setting_63: value_63
globex_setting_64: value_64
globex_setting_65: value_65
globex_setting_66: value_66
globex_setting_67: value_67
globex_setting_68: value_68
globex_setting_69: value_69
globex_setting_70: value_70
globex_setting_71: value_71
globex_setting_72: value_72
globex_setting_73: value_73
globex_setting_74: value_74
globex_setting_75: value_75
globex_setting_76: value_76
globex_setting_77: value_77
globex_setting_78: value_78
globex_setting_79: value_79
globex_setting_80: value_80
globex_setting_81: value_81
globex_setting_82: value_82
globex_setting_83: value_83
globex_setting_84: value_84
globex_setting_85: value_85
globex_setting_86: value_86
globex_setting_87: value_87
globex_setting_88: value_88
globex_setting_89: value_89
globex_setting_90: value_90
globex_setting_91: value_91
globex_setting_92: value_92
globex_setting_93: value_93
globex_setting_94: value_94
globex_setting_95: value_95
globex_setting_96: value_96
globex_setting_97: value_97
globex_setting_98: value_98
globex_setting_99: value_99
globex_setting_100: value_100
globex_setting_101: value_101
globex_setting_102: value_102
globex_setting_103: value_103
globex_setting_104: value_104
globex_setting_105: value_105
globex_setting_106: value_106
globex_setting_107: value_107
globex_setting_108: value_108
globex_setting_109: value_109
globex_setting_110: value_110
globex_setting_111: value_111
globex_setting_112: value_112
globex_setting_113: value_113
globex_setting_114: value_114
globex_setting_115: value_115
globex_setting_116: value_116
globex_setting_117: value_117
globex_setting_118: value_118
globex_setting_119: value_119
globex_setting_120: value_120
globex_setting_121: value_121
globex_setting_122: value_122
globex_setting_123: value_123
globex_setting_124: value_124
globex_setting_125: value_125
globex_setting_126: value_126
globex_setting_127: value_127
globex_setting_128: value_128
globex_setting_129: value_129
globex_setting_130: value_130
globex_setting_131: value_131
globex_setting_132: value_132
globex_setting_133: value_133
globex_setting_134: value_134
globex_setting_135: value_135
globex_setting_136: value_136
globex_setting_137: value_137
globex_setting_138: value_138
globex_setting_139: value_139
globex_setting_140: value_140
globex_setting_141: value_141
globex_setting_142: value_142
globex_setting_143: value_143
globex_setting_144: value_144
globex_setting_145: value_145
globex_setting_146: value_146
globex_setting_147: value_147
globex_setting_148: value_148
globex_setting_149: value_149